name: CI-CD

on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  ci:
    runs-on: ubuntu-latest
    steps: 
      - name: Autenticar no Docker Hub
        run: echo "Executanto o comando Docker Login"
      - name: Contrução da Imagem Docker
        run: echo "Executanto o comando Docker Build"
      - name: Evio da Imagem Docker
        run: echo "Executanto o comando Docker push"

  cd:
    runs-on: ubuntu-latest
    needs: [ci]
    steps: 
      - name: Autenticar na AWS
        run: echo "Executanto o comando aws configure"
      - name: Configurar o kubectl
        run: echo "Executanto o comando aws eks update-kubeconfig"
      - name: Deploy dos manifestos no Kubernetes
        run: echo "Executanto o comando kubectl apply"
      

